<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * KT_Instagram widget class
 *
 * @since 1.0
 */
class Widget_KT_Flickr extends WP_Widget {
    
    public function __construct() {
        $widget_ops = array('classname' => 'widget_kt_flickr', 'description' => __( "Lasted images in flickr.", KT_THEME_LANG) );
        parent::__construct('kt_flickr', __('KT: Flickr', KT_THEME_LANG), $widget_ops);
    }

    public function widget($args, $instance) {

        $title = apply_filters( 'widget_title', empty( $instance['title'] ) ? '' : $instance['title'], $instance, $this->id_base );
        $user_id = $instance['user_id'];
        $number = $instance['number'];
        $column = $instance['column'];
        $api = $instance['api'];
        
        echo $args['before_widget'];
        if ( $title ) {
            echo $args['before_title'] . $title . $args['after_title'];
        }
            
        ?>
            <?php if( $user_id && $number && $api ){ ?>
                <div class="kt_flickr clearfix column-<?php echo $column; ?>">
                    <script type="text/javascript">
                		function jsonFlickrApi(rsp) {
                            console.log(rsp);
                			if (rsp.stat != "ok"){
                				// If this executes, something broke!
                				return;
                			}
                			//variable "s" is going to contain
                			//all the markup that is generated by the loop below
                			var s = "";
                
                			//this loop runs through every item and creates HTML
                			for (var i=0; i < rsp.photos.photo.length; i++) {
                				photo = rsp.photos.photo[ i ];
                
                				//notice that "t.jpg" is where you change the
                				//size of the image
                				t_url = "http://farm" + photo.farm +
                				".static.flickr.com/" + photo.server + "/" +
                				photo.id + "_" + photo.secret + "_" + "s.jpg";
                
                				p_url = "http://www.flickr.com/photos/" +
                				photo.owner + "/" + photo.id;
                
                				s +=  '<a target="_blank" href="' + p_url + '">' + '<img alt="'+
                				photo.title + '"src="' + t_url + '"/>' + '</a>';
                			}
                
                			document.write(s);
                		}
                		</script>
                		<script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;user_id=<?php echo $user_id; ?>&amp;api_key=<?php echo $api; ?>&amp;media=photos&amp;per_page=<?php echo $number; ?>&amp;privacy_filter=1"></script>
                		<script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;group_id=<?php echo $user_id; ?>&amp;api_key=<?php echo $api; ?>&amp;media=photos&amp;per_page=<?php echo $number; ?>&amp;privacy_filter=1"></script>
                </div>
            <?php } ?>
        <?php  
        
        echo $args['after_widget'];
        
    }

    public function update( $new_instance, $old_instance ) {
        $instance = $old_instance;
        $instance['title'] = strip_tags($new_instance['title']);
        $instance['user_id'] = $new_instance['user_id'];
        $instance['api'] = $new_instance['api'];
        
        $instance['number'] = (int) $new_instance['number'];
        if(!$instance['number']){
            $instance['number'] = 9;
        }
        $instance['column'] = $new_instance['column'];
        if(!$instance['column']){
            $instance['column'] = 3;
        }

        return $instance;
    }


    public function form( $instance ) {

        $defaults = array( 'title' => __( 'Flickr' , KT_THEME_LANG), 'type' => '', 'user_id' => '', 'number' => 9, 'ordering' => '', 'column' => 3, 'api' => '6346cf3fc74387e93b84f0d22c78939a' );
        $instance = wp_parse_args( (array) $instance, $defaults );

        $title = strip_tags($instance['title']);

        ?>

        <p><label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:' ); ?></label>
            <input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo $title; ?>" /></p>
        
        <p><label for="<?php echo $this->get_field_id( 'user_id' ); ?>"><?php _e( 'Flickr ID:' ); ?></label>
            <input class="widefat" id="<?php echo $this->get_field_id( 'user_id' ); ?>" name="<?php echo $this->get_field_name( 'user_id' ); ?>" type="text" value="<?php echo $instance['user_id']; ?>" />
            <small><?php _e('To find your flickID visit',KT_THEME_LANG); ?> <a target="_blank" href="http://idgettr.com/"><?php _e('idGettr.',KT_THEME_LANG); ?></a></small>
        </p>
        
        <p><label for="<?php echo $this->get_field_id( 'number' ); ?>"><?php _e( 'Number of image to show:', KT_THEME_LANG ); ?></label>
            <input id="<?php echo $this->get_field_id( 'number' ); ?>" name="<?php echo $this->get_field_name( 'number' ); ?>" type="text" value="<?php echo $instance['number']; ?>" class="widefat" />
            <small><?php _e('Select number of photos to display.',KT_THEME_LANG); ?></small>
        </p>
        
        <p><label for="<?php echo $this->get_field_id( 'column' ); ?>"><?php _e( 'Column of images:', KT_THEME_LANG ); ?></label>
            <select class="widefat" id="<?php echo $this->get_field_id('column'); ?>" name="<?php echo $this->get_field_name('column'); ?>">
                <option <?php selected( $instance['column'], '2' ); ?> value="2"><?php _e('2',KT_THEME_LANG); ?></option>
                <option <?php selected( $instance['column'], '3' ); ?> value="3"><?php _e('3',KT_THEME_LANG); ?></option>
                <option <?php selected( $instance['column'], '4' ); ?> value="4"><?php _e('4',KT_THEME_LANG); ?></option>
            </select>
            <small><?php _e('Select column of image.',KT_THEME_LANG); ?></small>
        </p>
        
        <p>
			<label for="<?php echo $this->get_field_id('api'); ?>">API key (Use default or get your own from <a href="http://www.flickr.com/services/apps/create/apply">Flickr APP Garden</a>):</label>
			<input class="widefat" type="text" id="<?php echo $this->get_field_id('api'); ?>" name="<?php echo $this->get_field_name('api'); ?>" value="<?php echo $instance['api']; ?>" />
			<small>Default key is: 6346cf3fc74387e93b84f0d22c78939a</small>
		</p>
    <?php
    }
}

/**
 * Register Widget_KT_Flickr widget
 *
 *
 */

register_widget('Widget_KT_Flickr');
